/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package br.com.iomrh.gui;

import br.com.iomrh.beans.Candidato;
import br.com.iomrh.beans.ExperienciaProfissional;
import br.com.iomrh.beans.Profissao;
import br.com.iomrh.dao.CandidatoDAO;
import br.com.iomrh.dao.ProfissaoDAO;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Italo Miranda
 */
public class FiltrarCandidato extends javax.swing.JFrame {

    /**
     * Creates new form Filtro
     */
    
    //Cria novo Model para adicionar/remover elementos do 2º jList
    DefaultListModel dlm2 = new DefaultListModel();
    
    public FiltrarCandidato() {
        initComponents();
        //buttonGroup1 está relacionado ao PNE
        buttonGroup1.add(Radio__Candidato__PortadorNecessidadesEspeciais__Sim);
        buttonGroup1.add(Radio__Candidato__PortadorNecessidadesEspeciais__Nao);
        //buttonGroup2 está relacionado ao DisponibilidadeViajar
        buttonGroup2.add(Radio__Candidato__DisponibilidadeViajar__Sim);
        buttonGroup2.add(Radio__Candidato__DisponibilidadeViajar__Nao);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jInternalFrame1 = new javax.swing.JInternalFrame();
        jTPResultado = new javax.swing.JTabbedPane();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        Field__Profissao__Nome__Pesquisa = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        List__Profissao__Nome__Lista = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        List__Profissao__Nome__Selecionados = new javax.swing.JList();
        addProfissao = new javax.swing.JButton();
        delProfissao = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        Button__Profissao__Nome__Pesquisar = new javax.swing.JButton();
        jPanel17 = new javax.swing.JPanel();
        jPanel18 = new javax.swing.JPanel();
        Button__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa = new javax.swing.JButton();
        Field__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        List__CaracteristicasCandidato__Nome__Lista = new javax.swing.JList();
        addCaracteristica = new javax.swing.JButton();
        delCaracteristica = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        Field__CaracteristicasCandidato__CaracteristicasCandidato__Selecionados = new javax.swing.JList();
        jPanel21 = new javax.swing.JPanel();
        jPanel22 = new javax.swing.JPanel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        Field__Candidato__dataNascimento = new javax.swing.JTextField();
        Field__Candidato__quantidadeFilhos = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        Field__Candidato__CPF = new javax.swing.JTextField();
        Field__Candidato__Nome = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        Radio__Candidato__PortadorNecessidadesEspeciais__Sim = new javax.swing.JRadioButton();
        Radio__Candidato__DisponibilidadeViajar__Nao = new javax.swing.JRadioButton();
        Radio__Candidato__DisponibilidadeViajar__Sim = new javax.swing.JRadioButton();
        Radio__Candidato__PortadorNecessidadesEspeciais__Nao = new javax.swing.JRadioButton();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        Combo__Candidato__CNHCategoria = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        Radio__Candidato__Veiculo = new javax.swing.JComboBox();
        jLabel55 = new javax.swing.JLabel();
        Radio__Candidato__PretensaoSalarial = new javax.swing.JTextField();
        Field__Candidato__PrimeiroEmprego = new javax.swing.JCheckBox();
        Checkbox__Candidato__Gerencia = new javax.swing.JCheckBox();
        Combo__Candidato__estadoCivil = new javax.swing.JComboBox();
        jPanel23 = new javax.swing.JPanel();
        jPanel24 = new javax.swing.JPanel();
        jLabel56 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        Table__IndisponibilidadeCandidato = new javax.swing.JTable();
        jPanel15 = new javax.swing.JPanel();
        jPanel16 = new javax.swing.JPanel();
        ComboBox__ExperienciaProfissional__CargoExercido__Pesquisa = new javax.swing.JComboBox();
        Field__ExperienciaProfissional__Duracao = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Button__ExperienciaProfissional__InserirExperiencia = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        Checkbox__ExperienciaProfissional__Gerente = new javax.swing.JCheckBox();
        jScrollPane8 = new javax.swing.JScrollPane();
        Table__ExperienciaProfissional = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table__ResultadoFiltragem = new javax.swing.JTable();
        jPanel19 = new javax.swing.JPanel();
        jPanel20 = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jScrollPane9 = new javax.swing.JScrollPane();
        Table__CurriculoInformatica = new javax.swing.JTable();
        jScrollPane7 = new javax.swing.JScrollPane();
        Table__CurriculoIdioma = new javax.swing.JTable();
        Filtrar = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jInternalFrame1.setVisible(true);

        jPanel14.setMaximumSize(new java.awt.Dimension(30000, 32767));
        jPanel14.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel14ComponentShown(evt);
            }
        });

        Field__Profissao__Nome__Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field__Profissao__Nome__PesquisaActionPerformed(evt);
            }
        });

        DefaultListModel dlm = new DefaultListModel();

        ProfissaoDAO pd = new ProfissaoDAO();
        List<Profissao> profissoes = pd.listarProfissoes();
        for(Profissao p : profissoes){
            dlm.addElement(p);
        }
        List__Profissao__Nome__Lista.setModel(dlm);
        jScrollPane1.setViewportView(List__Profissao__Nome__Lista);

        List__Profissao__Nome__Selecionados.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(List__Profissao__Nome__Selecionados);

        addProfissao.setText("->");
        addProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProfissaoActionPerformed(evt);
            }
        });

        delProfissao.setText("<-");
        delProfissao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                delProfissaoActionPerformed(evt);
            }
        });

        jLabel2.setText("Pesquisar:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel14Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Field__Profissao__Nome__Pesquisa)))
                .addGap(67, 67, 67)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addProfissao)
                    .addComponent(delProfissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap(52, Short.MAX_VALUE)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Field__Profissao__Nome__Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(addProfissao)
                        .addGap(34, 34, 34)
                        .addComponent(delProfissao)
                        .addGap(50, 50, 50))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        Button__Profissao__Nome__Pesquisar.setText("Pesquisar");

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addGap(284, 284, 284)
                .addComponent(Button__Profissao__Nome__Pesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button__Profissao__Nome__Pesquisar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPResultado.addTab("Profissões/Cargos", jPanel13);

        jPanel18.setForeground(new java.awt.Color(255, 255, 255));
        jPanel18.setToolTipText("");

        Button__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa.setText("Pesquisar");

        Field__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field__CaracteristicasCandidato__CaracteristicasCandidato__PesquisaActionPerformed(evt);
            }
        });

        jLabel3.setText("Pesquisar");

        List__CaracteristicasCandidato__Nome__Lista.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(List__CaracteristicasCandidato__Nome__Lista);

        addCaracteristica.setText("->");

        delCaracteristica.setText("<-");

        Field__CaracteristicasCandidato__CaracteristicasCandidato__Selecionados.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(Field__CaracteristicasCandidato__CaracteristicasCandidato__Selecionados);

        javax.swing.GroupLayout jPanel18Layout = new javax.swing.GroupLayout(jPanel18);
        jPanel18.setLayout(jPanel18Layout);
        jPanel18Layout.setHorizontalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Button__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(Field__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(66, 66, 66)
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addCaracteristica)
                    .addComponent(delCaracteristica))
                .addGap(104, 104, 104)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel18Layout.setVerticalGroup(
            jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel18Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Field__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(addCaracteristica)
                        .addGap(43, 43, 43)
                        .addComponent(delCaracteristica))
                    .addGroup(jPanel18Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel18Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 223, Short.MAX_VALUE)
                            .addComponent(jScrollPane4))))
                .addGap(3, 3, 3)
                .addComponent(Button__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel17Layout = new javax.swing.GroupLayout(jPanel17);
        jPanel17.setLayout(jPanel17Layout);
        jPanel17Layout.setHorizontalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );
        jPanel17Layout.setVerticalGroup(
            jPanel17Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel17Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jPanel18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(55, Short.MAX_VALUE))
        );

        jTPResultado.addTab("Características", jPanel17);

        jLabel45.setText("Qtd. de filhos");

        jLabel46.setText("Estado civil");

        Field__Candidato__dataNascimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Field__Candidato__dataNascimentoActionPerformed(evt);
            }
        });

        jLabel48.setText("Nome");

        jLabel49.setText("CPF");

        jLabel50.setText("Data de nascimento");

        jLabel51.setText("PNE");

        Radio__Candidato__PortadorNecessidadesEspeciais__Sim.setText("Sim");

        Radio__Candidato__DisponibilidadeViajar__Nao.setText("Não");

        Radio__Candidato__DisponibilidadeViajar__Sim.setText("Sim");

        Radio__Candidato__PortadorNecessidadesEspeciais__Nao.setText("Não");

        jLabel52.setText("Disp. viajar");

        jLabel53.setText("CNH");

        Combo__Candidato__CNHCategoria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não possui", "A", "B", "C", "D", "E" }));

        jLabel54.setText("Veículo");

        Radio__Candidato__Veiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Não possui", "Carro", "Moto", "Outro", " " }));

        jLabel55.setText("Pretensão salarial");

        Field__Candidato__PrimeiroEmprego.setText("Primeiro emprego");

        Checkbox__Candidato__Gerencia.setText("Gerência");

        Combo__Candidato__estadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Casado(a)", "Solteiro(a)", "Divorciado(a)", "Viúvo(a)", "Outros" }));

        javax.swing.GroupLayout jPanel22Layout = new javax.swing.GroupLayout(jPanel22);
        jPanel22.setLayout(jPanel22Layout);
        jPanel22Layout.setHorizontalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addComponent(Field__Candidato__PrimeiroEmprego)
                        .addGap(18, 18, 18)
                        .addComponent(Checkbox__Candidato__Gerencia))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel48)
                                    .addComponent(jLabel49))
                                .addGap(78, 78, 78))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel22Layout.createSequentialGroup()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel46)
                                    .addComponent(jLabel50)
                                    .addComponent(jLabel45))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Field__Candidato__CPF)
                            .addComponent(Field__Candidato__Nome)
                            .addComponent(Field__Candidato__dataNascimento)
                            .addComponent(Field__Candidato__quantidadeFilhos)
                            .addComponent(Combo__Candidato__estadoCivil, 0, 218, Short.MAX_VALUE))
                        .addGap(54, 54, 54)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addComponent(jLabel53)
                            .addComponent(jLabel54)
                            .addComponent(jLabel55))
                        .addGap(21, 21, 21)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Radio__Candidato__PortadorNecessidadesEspeciais__Sim)
                            .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(Radio__Candidato__PortadorNecessidadesEspeciais__Nao)
                                .addGroup(jPanel22Layout.createSequentialGroup()
                                    .addComponent(Radio__Candidato__DisponibilidadeViajar__Sim)
                                    .addGap(29, 29, 29)
                                    .addComponent(Radio__Candidato__DisponibilidadeViajar__Nao)))
                            .addComponent(Combo__Candidato__CNHCategoria, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Radio__Candidato__Veiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Radio__Candidato__PretensaoSalarial))))
                .addContainerGap(102, Short.MAX_VALUE))
        );
        jPanel22Layout.setVerticalGroup(
            jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel22Layout.createSequentialGroup()
                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field__Candidato__Nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel48))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field__Candidato__CPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel49))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field__Candidato__dataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel50))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(Combo__Candidato__estadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field__Candidato__quantidadeFilhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel45))
                        .addGap(28, 28, 28))
                    .addGroup(jPanel22Layout.createSequentialGroup()
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addComponent(jLabel51)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel52)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel53)
                                .addGap(19, 19, 19)
                                .addComponent(jLabel54))
                            .addGroup(jPanel22Layout.createSequentialGroup()
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Radio__Candidato__PortadorNecessidadesEspeciais__Sim)
                                    .addComponent(Radio__Candidato__PortadorNecessidadesEspeciais__Nao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(Radio__Candidato__DisponibilidadeViajar__Sim)
                                    .addComponent(Radio__Candidato__DisponibilidadeViajar__Nao))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Combo__Candidato__CNHCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Radio__Candidato__Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel55)
                            .addComponent(Radio__Candidato__PretensaoSalarial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel22Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Field__Candidato__PrimeiroEmprego)
                            .addComponent(Checkbox__Candidato__Gerencia))))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel21Layout = new javax.swing.GroupLayout(jPanel21);
        jPanel21.setLayout(jPanel21Layout);
        jPanel21Layout.setHorizontalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 939, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(219, Short.MAX_VALUE)))
        );
        jPanel21Layout.setVerticalGroup(
            jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
            .addGroup(jPanel21Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel21Layout.createSequentialGroup()
                    .addContainerGap(94, Short.MAX_VALUE)
                    .addComponent(jPanel22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(88, Short.MAX_VALUE)))
        );

        jTPResultado.addTab("Dados pessoais", jPanel21);

        jLabel56.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel56.setText("Indisponibilidade do candidato");

        Table__IndisponibilidadeCandidato.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"Manhã", null, null, null, null, null, null, null, "COLOCAR BOTÃO"},
                {"Tarde", null, null, null, null, null, null, null, "COLOCAR BOTÃO"},
                {"Noite", null, null, null, null, null, null, null, "COLOCAR BOTÃO"}
            },
            new String [] {
                "Dia/turno", "Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado", "Desmarcar linha"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Boolean.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane6.setViewportView(Table__IndisponibilidadeCandidato);

        javax.swing.GroupLayout jPanel24Layout = new javax.swing.GroupLayout(jPanel24);
        jPanel24.setLayout(jPanel24Layout);
        jPanel24Layout.setHorizontalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addGroup(jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel24Layout.setVerticalGroup(
            jPanel24Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel24Layout.createSequentialGroup()
                .addComponent(jLabel56)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel24, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        jTPResultado.addTab("Indisponiblidade do candidato", jPanel23);

        ComboBox__ExperienciaProfissional__CargoExercido__Pesquisa.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Cargo");

        jLabel9.setText("Duração");

        Button__ExperienciaProfissional__InserirExperiencia.setText("Inserir experiência");

        jLabel4.setText("Gerente?");

        Table__ExperienciaProfissional.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cargo", "Duração", "Gerente", "Remover"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                true, true, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane8.setViewportView(Table__ExperienciaProfissional);
        if (Table__ExperienciaProfissional.getColumnModel().getColumnCount() > 0) {
            Table__ExperienciaProfissional.getColumnModel().getColumn(1).setPreferredWidth(8);
            Table__ExperienciaProfissional.getColumnModel().getColumn(2).setResizable(false);
            Table__ExperienciaProfissional.getColumnModel().getColumn(2).setPreferredWidth(2);
            Table__ExperienciaProfissional.getColumnModel().getColumn(3).setResizable(false);
            Table__ExperienciaProfissional.getColumnModel().getColumn(3).setPreferredWidth(4);
        }

        javax.swing.GroupLayout jPanel16Layout = new javax.swing.GroupLayout(jPanel16);
        jPanel16.setLayout(jPanel16Layout);
        jPanel16Layout.setHorizontalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboBox__ExperienciaProfissional__CargoExercido__Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Field__ExperienciaProfissional__Duracao, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Checkbox__ExperienciaProfissional__Gerente)))
                    .addComponent(Button__ExperienciaProfissional__InserirExperiencia)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 784, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        jPanel16Layout.setVerticalGroup(
            jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel16Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addComponent(ComboBox__ExperienciaProfissional__CargoExercido__Pesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Field__ExperienciaProfissional__Duracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel16Layout.createSequentialGroup()
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addGroup(jPanel16Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel9)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel16Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Checkbox__ExperienciaProfissional__Gerente))))
                .addGap(18, 18, 18)
                .addComponent(Button__ExperienciaProfissional__InserirExperiencia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(259, 259, 259))
        );

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel15Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTPResultado.addTab("Experiência profissional", jPanel15);

        Table__ResultadoFiltragem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Código", "Nome Completo", "Profissão", "Marcar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(Table__ResultadoFiltragem);

        jTPResultado.addTab("Resultado Filtragem", jScrollPane3);

        jPanel20.setForeground(new java.awt.Color(255, 255, 255));
        jPanel20.setToolTipText("");

        jLabel41.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel41.setText("Informática");

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Idiomas");

        Table__CurriculoInformatica.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Habilidade", "Nível", "Marcar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane9.setViewportView(Table__CurriculoInformatica);
        if (Table__CurriculoInformatica.getColumnModel().getColumnCount() > 0) {
            Table__CurriculoInformatica.getColumnModel().getColumn(2).setResizable(false);
            Table__CurriculoInformatica.getColumnModel().getColumn(2).setPreferredWidth(4);
        }

        Table__CurriculoIdioma.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Nível fala", "Nível Escrita", "Nível Leitura", "Marcar"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane7.setViewportView(Table__CurriculoIdioma);
        if (Table__CurriculoIdioma.getColumnModel().getColumnCount() > 0) {
            Table__CurriculoIdioma.getColumnModel().getColumn(4).setResizable(false);
            Table__CurriculoIdioma.getColumnModel().getColumn(4).setPreferredWidth(5);
        }

        javax.swing.GroupLayout jPanel20Layout = new javax.swing.GroupLayout(jPanel20);
        jPanel20.setLayout(jPanel20Layout);
        jPanel20Layout.setHorizontalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel41)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel42))
                .addContainerGap())
        );
        jPanel20Layout.setVerticalGroup(
            jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel20Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(jLabel41))
                .addGap(18, 18, 18)
                .addGroup(jPanel20Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 337, Short.MAX_VALUE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel19Layout = new javax.swing.GroupLayout(jPanel19);
        jPanel19.setLayout(jPanel19Layout);
        jPanel19Layout.setHorizontalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel19Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel19Layout.setVerticalGroup(
            jPanel19Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel19Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTPResultado.addTab("Informática/Idiomas", jPanel19);

        Filtrar.setText("Filtrar");
        Filtrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FiltrarActionPerformed(evt);
            }
        });

        jButton4.setText("Desfazer todos os filtros");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setText("Filtrar candidatos por:");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTPResultado)
                    .addGroup(jInternalFrame1Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jInternalFrame1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jButton4)
                .addGap(30, 30, 30)
                .addComponent(Filtrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jInternalFrame1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTPResultado, javax.swing.GroupLayout.PREFERRED_SIZE, 434, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(Filtrar))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jInternalFrame1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void FiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FiltrarActionPerformed
        
        //Pega tamanho da lista de profissões selecionadas pelo usuário
        int tamanhoLista = List__Profissao__Nome__Selecionados.getModel().getSize();
        //Cria arrayList de profissões selecionadas pelo usuário
        List<Profissao> profissoes = new ArrayList<>();
        //Adiciona as profissões selecionadas pelo usuário ao arrayList
        for (int i=0; i < tamanhoLista; i++){
            profissoes.add((Profissao) List__Profissao__Nome__Selecionados.getModel().getElementAt(i));
        }
        
        //Busca todos os candidatos que possuem uma das profissões acima
        List<Candidato> candidatosProfissoes = new ArrayList<Candidato>();
        CandidatoDAO candidadoProfissoesDao = new CandidatoDAO();
        for(Profissao prof : profissoes){
            Candidato canTemp = new Candidato();
            canTemp.setCodProfissao(prof.getCodigoProfissao());
            candidatosProfissoes.addAll(candidadoProfissoesDao.buscaCandidato(canTemp));
        }
       
        
        
        //Pega tamanho da lista de Experiências profissionais selecionadas pelo usuário
        int tamanhoListaExperienciaProfissional = Table__ExperienciaProfissional.getRowCount();
        //Cria arrayList de Experiências profissionais selecionadas pelo usuário
        List<ExperienciaProfissional> experienciasProfissionais = new ArrayList<>();
        //Adiciona as Experiências profissionais selecionadas pelo usuário
        for (int i=0; i < tamanhoListaExperienciaProfissional; i++){
            ExperienciaProfissional expProTemp = new ExperienciaProfissional();
            expProTemp.setCodigoProfissao((Integer) Table__ExperienciaProfissional.getValueAt(i, 0));
            expProTemp.setDuracao((Integer) Table__ExperienciaProfissional.getValueAt(i, 1));
            //expProTemp.setGerencia((String) dtm.getValueAt(i,2));
            experienciasProfissionais.add(expProTemp);
        }
        //Busca todos os candidatos que possuem uma das profissões acima
        List<Candidato> candidatosExpProfissional = new ArrayList<Candidato>();     
        CandidatoDAO candidadoDaoExpPro = new CandidatoDAO();
        if(!experienciasProfissionais.isEmpty()){
            for(ExperienciaProfissional expPro : experienciasProfissionais){
                Candidato canTemp = new Candidato();
                canTemp.addExperienciaProfissionalList(expPro);
                candidatosExpProfissional.addAll(candidadoDaoExpPro.buscaCandidato(canTemp));
            }
        }
        
        
        //Cria objeto do tipo DefaultTableModel
        javax.swing.table.DefaultTableModel dtm = (javax.swing.table.DefaultTableModel) Table__ResultadoFiltragem.getModel();
        for(Candidato c : candidatosProfissoes){
                dtm.addRow(new Object[]{c.getCodigoCandidato(), c.getPrenome(), 1, false});
        }
        
        jTPResultado.setSelectedIndex(1);
      
    }//GEN-LAST:event_FiltrarActionPerformed

    private void Field__CaracteristicasCandidato__CaracteristicasCandidato__PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field__CaracteristicasCandidato__CaracteristicasCandidato__PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field__CaracteristicasCandidato__CaracteristicasCandidato__PesquisaActionPerformed

    private void jPanel14ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel14ComponentShown

    }//GEN-LAST:event_jPanel14ComponentShown

    private void delProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_delProfissaoActionPerformed
        List<Profissao> lista = List__Profissao__Nome__Selecionados.getSelectedValuesList();
        for(Profissao l : lista){
            dlm2.removeElement(l);
        }
        List__Profissao__Nome__Selecionados.setModel(dlm2);
    }//GEN-LAST:event_delProfissaoActionPerformed

    private void addProfissaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProfissaoActionPerformed
        List<Profissao> lista = List__Profissao__Nome__Lista.getSelectedValuesList();
        for(Profissao l : lista){
            dlm2.addElement(l);
        }

        List__Profissao__Nome__Selecionados.setModel(dlm2);
    }//GEN-LAST:event_addProfissaoActionPerformed

    private void Field__Profissao__Nome__PesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field__Profissao__Nome__PesquisaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field__Profissao__Nome__PesquisaActionPerformed

    private void Field__Candidato__dataNascimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Field__Candidato__dataNascimentoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Field__Candidato__dataNascimentoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa;
    private javax.swing.JButton Button__ExperienciaProfissional__InserirExperiencia;
    private javax.swing.JButton Button__Profissao__Nome__Pesquisar;
    private javax.swing.JCheckBox Checkbox__Candidato__Gerencia;
    private javax.swing.JCheckBox Checkbox__ExperienciaProfissional__Gerente;
    private javax.swing.JComboBox ComboBox__ExperienciaProfissional__CargoExercido__Pesquisa;
    private javax.swing.JComboBox Combo__Candidato__CNHCategoria;
    private javax.swing.JComboBox Combo__Candidato__estadoCivil;
    private javax.swing.JTextField Field__Candidato__CPF;
    private javax.swing.JTextField Field__Candidato__Nome;
    private javax.swing.JCheckBox Field__Candidato__PrimeiroEmprego;
    private javax.swing.JTextField Field__Candidato__dataNascimento;
    private javax.swing.JTextField Field__Candidato__quantidadeFilhos;
    private javax.swing.JTextField Field__CaracteristicasCandidato__CaracteristicasCandidato__Pesquisa;
    private javax.swing.JList Field__CaracteristicasCandidato__CaracteristicasCandidato__Selecionados;
    private javax.swing.JTextField Field__ExperienciaProfissional__Duracao;
    private javax.swing.JTextField Field__Profissao__Nome__Pesquisa;
    private javax.swing.JButton Filtrar;
    private javax.swing.JList List__CaracteristicasCandidato__Nome__Lista;
    private javax.swing.JList List__Profissao__Nome__Lista;
    private javax.swing.JList List__Profissao__Nome__Selecionados;
    private javax.swing.JRadioButton Radio__Candidato__DisponibilidadeViajar__Nao;
    private javax.swing.JRadioButton Radio__Candidato__DisponibilidadeViajar__Sim;
    private javax.swing.JRadioButton Radio__Candidato__PortadorNecessidadesEspeciais__Nao;
    private javax.swing.JRadioButton Radio__Candidato__PortadorNecessidadesEspeciais__Sim;
    private javax.swing.JTextField Radio__Candidato__PretensaoSalarial;
    private javax.swing.JComboBox Radio__Candidato__Veiculo;
    private javax.swing.JTable Table__CurriculoIdioma;
    private javax.swing.JTable Table__CurriculoInformatica;
    private javax.swing.JTable Table__ExperienciaProfissional;
    private javax.swing.JTable Table__IndisponibilidadeCandidato;
    private javax.swing.JTable Table__ResultadoFiltragem;
    private javax.swing.JButton addCaracteristica;
    private javax.swing.JButton addProfissao;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton delCaracteristica;
    private javax.swing.JButton delProfissao;
    private javax.swing.JButton jButton4;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel20;
    private javax.swing.JPanel jPanel21;
    private javax.swing.JPanel jPanel22;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JPanel jPanel24;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTPResultado;
    // End of variables declaration//GEN-END:variables
}
